[workspace]
channels = ["https://prefix.dev/pixi-build-backends", "https://prefix.dev/robostack-kilted", "https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64"]
preview = ["pixi-build"]

[tasks]
build = "colcon build --event-handlers console_direct+ --cmake-force-configure --cmake-args -DBUILD_TESTING=OFF -DCMAKE_CXX_FLAGS=-Wno-error "
test = "colcon test"

[dev]
ros-kilted-navigation2 = { path = "navigation2/package.xml" }
ros-kilted-nav2-amcl = {path = "nav2_amcl/package.xml"}
ros-kilted-nav2-behavior-tree = {path = "nav2_behavior_tree/package.xml"}
ros-kilted-nav2-behaviors = {path = "nav2_behaviors/package.xml"}
ros-kilted-nav2-bringup = {path = "nav2_bringup/package.xml"}
ros-kilted-nav2-bt-navigator = {path = "nav2_bt_navigator/package.xml"}
ros-kilted-nav2-collision-monitor = {path = "nav2_collision_monitor/package.xml"}
ros-kilted-nav2-common = {path = "nav2_common/package.xml"}
ros-kilted-nav2-constrained-smoother = {path = "nav2_constrained_smoother/package.xml"}
ros-kilted-nav2-controller = {path = "nav2_controller/package.xml"}
ros-kilted-nav2-core = {path = "nav2_core/package.xml"}
ros-kilted-nav2-costmap-2d = {path = "nav2_costmap_2d/package.xml"}
ros-kilted-opennav-docking = {path = "nav2_docking/opennav_docking/package.xml"}
ros-kilted-opennav-docking-bt = {path = "nav2_docking/opennav_docking_bt/package.xml"}
ros-kilted-opennav-docking-core = {path = "nav2_docking/opennav_docking_core/package.xml"}
ros-kilted-costmap-queue = {path = "nav2_dwb_controller/costmap_queue/package.xml"}
ros-kilted-dwb-core = {path = "nav2_dwb_controller/dwb_core/package.xml"}
ros-kilted-dwb-critics = {path = "nav2_dwb_controller/dwb_critics/package.xml"}
ros-kilted-dwb-msgs = {path = "nav2_dwb_controller/dwb_msgs/package.xml"}
ros-kilted-dwb-plugins = {path = "nav2_dwb_controller/dwb_plugins/package.xml"}
ros-kilted-nav2-dwb-controller = {path = "nav2_dwb_controller/nav2_dwb_controller/package.xml"}
ros-kilted-nav-2d-msgs = {path = "nav2_dwb_controller/nav_2d_msgs/package.xml"}
ros-kilted-nav-2d-utils = {path = "nav2_dwb_controller/nav_2d_utils/package.xml"}
ros-kilted-nav2-graceful-controller = {path = "nav2_graceful_controller/package.xml"}
ros-kilted-nav2-lifecycle-manager = {path = "nav2_lifecycle_manager/package.xml"}
ros-kilted-nav2-loopback-sim = {path = "nav2_loopback_sim/package.xml"}
ros-kilted-nav2-map-server = {path = "nav2_map_server/package.xml"}
ros-kilted-nav2-mppi-controller = {path = "nav2_mppi_controller/package.xml"}
ros-kilted-nav2-msgs = {path = "nav2_msgs/package.xml"}
ros-kilted-nav2-navfn-planner = {path = "nav2_navfn_planner/package.xml"}
ros-kilted-nav2-planner = {path = "nav2_planner/package.xml"}
ros-kilted-nav2-regulated-pure-pursuit-controller = {path = "nav2_regulated_pure_pursuit_controller/package.xml"}
ros-kilted-nav2-rotation-shim-controller = {path = "nav2_rotation_shim_controller/package.xml"}
ros-kilted-nav2-route = {path = "nav2_route/package.xml"}
# [ 66%] Linking CXX shared library libnav2_rviz_plugins.so
# /root/navigation2/.pixi/envs/default/bin/../lib/gcc/x86_64-conda-linux-gnu/14.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find /root/navigation2/.pixi/envs/default/opt/rviz_ogre_vendor/lib/libOgreOverlay.so: No such file or directory
# /root/navigation2/.pixi/envs/default/bin/../lib/gcc/x86_64-conda-linux-gnu/14.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find /root/navigation2/.pixi/envs/default/opt/rviz_ogre_vendor/lib/libOgreMain.so: No such file or directory
# collect2: error: ld returned 1 exit status
# gmake[2]: *** [CMakeFiles/nav2_rviz_plugins.dir/build.make:658: libnav2_rviz_plugins.so] Error 1
# gmake[1]: *** [CMakeFiles/Makefile2:156: CMakeFiles/nav2_rviz_plugins.dir/all] Error 2
# gmake: *** [Makefile:146: all] Error 2
# Failed   <<< nav2_rviz_plugins [41.2s, exited with code 2]
# ros-kilted-nav2-rviz-plugins = {path = "nav2_rviz_plugins"}
ros-kilted-nav2-simple-commander = {path = "nav2_simple_commander/package.xml"}
ros-kilted-nav2-smac-planner = {path = "nav2_smac_planner/package.xml"}
ros-kilted-nav2-smoother = {path = "nav2_smoother/package.xml"}
ros-kilted-nav2-system-tests = {path = "nav2_system_tests/package.xml"}
ros-kilted-nav2-theta-star-planner = {path = "nav2_theta_star_planner/package.xml"}
ros-kilted-nav2-util = {path = "nav2_util/package.xml"}
ros-kilted-nav2-velocity-smoother = {path = "nav2_velocity_smoother/package.xml"}
ros-kilted-nav2-voxel-grid = {path = "nav2_voxel_grid/package.xml"}
ros-kilted-nav2-waypoint-follower = {path = "nav2_waypoint_follower/package.xml"}
ros-kilted-nav2-ros-common = { path = "nav2_ros_common/package.xml" }
ros-kilted-opennav-following = {path = "nav2_following/opennav_following/package.xml"}

[dependencies]
colcon-ros = ">=0.5.0,<0.6"
setuptools = "<72.0.0"
cmake = "<4"
nanoflann = ">=1.6.1,<2"

[target.linux-64.dependencies]
gcc_linux-64 = "<15"
