[workspace]
channels = ["https://prefix.dev/pixi-build-backends", "https://prefix.dev/robostack-jazzy", "https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64"]
preview = ["pixi-build"]

[tasks]
build = "colcon build --cmake-force-configure --cmake-args -DBUILD_TESTING=OFF -DCMAKE_CXX_FLAGS=-Wno-error "
test = "colcon test"

[dev]
ros-jazzy-navigation2 = { path = "navigation2/package.xml" }
ros-jazzy-nav2-amcl = {path = "nav2_amcl/package.xml"}
ros-jazzy-nav2-behavior-tree = {path = "nav2_behavior_tree/package.xml"}
ros-jazzy-nav2-behaviors = {path = "nav2_behaviors/package.xml"}
ros-jazzy-nav2-bringup = {path = "nav2_bringup/package.xml"}
ros-jazzy-nav2-bt-navigator = {path = "nav2_bt_navigator/package.xml"}
ros-jazzy-nav2-collision-monitor = {path = "nav2_collision_monitor/package.xml"}
ros-jazzy-nav2-common = {path = "nav2_common/package.xml"}
ros-jazzy-nav2-constrained-smoother = {path = "nav2_constrained_smoother/package.xml"}
ros-jazzy-nav2-controller = {path = "nav2_controller/package.xml"}
ros-jazzy-nav2-core = {path = "nav2_core/package.xml"}
ros-jazzy-nav2-costmap-2d = {path = "nav2_costmap_2d/package.xml"}
ros-jazzy-opennav-docking = {path = "nav2_docking/opennav_docking/package.xml"}
ros-jazzy-opennav-docking-bt = {path = "nav2_docking/opennav_docking_bt/package.xml"}
ros-jazzy-opennav-docking-core = {path = "nav2_docking/opennav_docking_core/package.xml"}
ros-jazzy-costmap-queue = {path = "nav2_dwb_controller/costmap_queue/package.xml"}
ros-jazzy-dwb-core = {path = "nav2_dwb_controller/dwb_core/package.xml"}
ros-jazzy-dwb-critics = {path = "nav2_dwb_controller/dwb_critics/package.xml"}
ros-jazzy-dwb-msgs = {path = "nav2_dwb_controller/dwb_msgs/package.xml"}
ros-jazzy-dwb-plugins = {path = "nav2_dwb_controller/dwb_plugins/package.xml"}
ros-jazzy-nav2-dwb-controller = {path = "nav2_dwb_controller/nav2_dwb_controller/package.xml"}
ros-jazzy-nav-2d-msgs = {path = "nav2_dwb_controller/nav_2d_msgs/package.xml"}
ros-jazzy-nav-2d-utils = {path = "nav2_dwb_controller/nav_2d_utils/package.xml"}
ros-jazzy-nav2-graceful-controller = {path = "nav2_graceful_controller/package.xml"}
ros-jazzy-nav2-lifecycle-manager = {path = "nav2_lifecycle_manager/package.xml"}
ros-jazzy-nav2-loopback-sim = {path = "nav2_loopback_sim/package.xml"}
ros-jazzy-nav2-map-server = {path = "nav2_map_server/package.xml"}
ros-jazzy-nav2-mppi-controller = {path = "nav2_mppi_controller/package.xml"}
ros-jazzy-nav2-msgs = {path = "nav2_msgs/package.xml"}
ros-jazzy-nav2-navfn-planner = {path = "nav2_navfn_planner/package.xml"}
ros-jazzy-nav2-planner = {path = "nav2_planner/package.xml"}
ros-jazzy-nav2-regulated-pure-pursuit-controller = {path = "nav2_regulated_pure_pursuit_controller/package.xml"}
ros-jazzy-nav2-rotation-shim-controller = {path = "nav2_rotation_shim_controller/package.xml"}
ros-jazzy-nav2-route = {path = "nav2_route/package.xml"}
ros-jazzy-nav2-rviz-plugins = {path = "nav2_rviz_plugins/package.xml"}
ros-jazzy-nav2-simple-commander = {path = "nav2_simple_commander/package.xml"}
ros-jazzy-nav2-smac-planner = {path = "nav2_smac_planner/package.xml"}
ros-jazzy-nav2-smoother = {path = "nav2_smoother/package.xml"}
ros-jazzy-nav2-system-tests = {path = "nav2_system_tests/package.xml"}
ros-jazzy-nav2-theta-star-planner = {path = "nav2_theta_star_planner/package.xml"}
ros-jazzy-nav2-util = {path = "nav2_util/package.xml"}
ros-jazzy-nav2-velocity-smoother = {path = "nav2_velocity_smoother/package.xml"}
ros-jazzy-nav2-voxel-grid = {path = "nav2_voxel_grid/package.xml"}
ros-jazzy-nav2-waypoint-follower = {path = "nav2_waypoint_follower/package.xml"}

[dependencies]
colcon-ros = ">=0.5.0,<0.6"
setuptools = "<72.0.0"
cmake = "<4"
nanoflann = ">=1.6.1,<2"
# ros-jazzy-desktop = ">=0.11.0,<0.12"
# ros-jazzy-turtlebot3-gazebo = ">=2.3.7,<3"

[target.linux-64.dependencies]
gcc_linux-64 = "<15"