name: Build

on:
  pull_request:
  push:
    branches:
      - main
      # TODO: REMOVE! For testing
      - pixi-main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: latest
          # Run the install with the `pixi exec` installed version
          run-install: false

      - name: Build
        # Trick to use a specific build of pixi
        run: pixi exec -c https://prefix.dev/ruben-arts pixi run build